export class Employee
{
    $key: string; //$key is used to store unique key automatically generated by firebase DB when we insert a new record.
    name: string;
    position: string;
    office: string;
    salary: number;

}
